# Generated by Django 4.0.5 on 2022-08-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('link', models.CharField(max_length=300, verbose_name='URl')),
                ('description', models.TextField(verbose_name='Loyiha haqida')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familyasi')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('Email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Telfon raqami')),
                ('address', models.CharField(max_length=299, verbose_name='Manzil')),
                ('skill', models.CharField(max_length=200, verbose_name='skill(Backend)')),
                ('languange', models.CharField(max_length=299, verbose_name='Qaysi tillarni bilasiz')),
                ('experience', models.CharField(max_length=200, verbose_name='Qancha vaqtdan beri ishlaysiz')),
            ],
        ),
        migrations.CreateModel(
            name='MyWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.myworkcategory')),
            ],
        ),
    ]
